### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by RTanner18** [purduesigbots/homebrew-pros#6]
```
Using pip 21.3.1 from /opt/homebrew/Cellar/pros-cli/3.2.2/libexec/lib/python3.9/site-packages/pip (python 3.9)
Processing /private/tmp/pros-cli--rfc6266-parser-20211117-5347-fj38d2/rfc6266-parser-0.0.6
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Warning: 'classifiers' should be a list, got type 'tuple'
  error in rfc6266-parser setup command: use_2to3 is invalid.
  Preparing metadata (setup.py): finished with status 'error'
WARNING: Discarding file:///private/tmp/pros-cli--rfc6266-parser-20211117-5347-fj38d2/rfc6266-parser-0.0.6. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by FoRJu** [comment]
I have faced the same issue. On two different mac platforms, 2020 MacBook Air with M1 and 2016 MacBookPro with intel processor.

After following instructions here:https://pros.cs.purdue.edu/v5/getting-started/macos.html
Did the following:

1. brew tap osx-cross/arm && brew install arm-gcc-bin 
2. brew tap purduesigbots/pros
3. brew install pros-cli

Got this message:

> Using pip 21.3.1 from /usr/local/Cellar/pros-cli/3.2.2/libexec/lib/python3.9/site-packages/pip (python 3.9)
> Processing /private/tmp/pros-cli--rfc6266-parser-20211119-13721-pqn3ka/rfc6266-parser-0.0.6
>   Preparing metadata (setup.py): started
>   Running command python setup.py egg_info
>   Warning: 'classifiers' should be a list, got type 'tuple'
>   error in rfc6266-parser setup command: use_2to3 is invalid.
>   Preparing metadata (setup.py): finished with status 'error'
> WARNING: Discarding file:///private/tmp/pros-cli--rfc6266-parser-20211119-13721-pqn3ka/rfc6266-parser-0.0.6. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
>   https://github.com/purduesigbots/homebrew-pros/issues

**Comment by kunwarsahni01** [comment]
This has been fixed and will be released soon https://github.com/purduesigbots/pros-cli/pull/182.

**Comment by FoRJu** [comment]
> This has been fixed and will be released soon [purduesigbots/pros-cli#182](https://github.com/purduesigbots/pros-cli/pull/182).

Thanks, kunwarsahni01. Do we know when it will be coming out? 3.2.2 is released in June.

If we are in a rush (always is during the season), would you recommend the alternative methods to instal pros-cli as below? I can only find the whl file for version 3.1.3.

> Install the CLI
> Install Python 3.6 or higher from the Python website.
> Install the CLI by downloading the latest version of the Python Wheel file (.whl) from here. Once downloaded, run python3 -m pip install ~/Downloads/pros-cli-v5_3.X.X-py3-none-any.whl (replacing that path with the path to which you downloaded the file).

**Comment by kunwarsahni01** [comment]
I'm working on the release process right now so should see the new version in the upcoming hours

**Comment by FoRJu** [comment]
Thanks a lot, Kunwar. Appreciate! We will be excitingly waiting for it.
